version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  web:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/partager
      - gem_data:/usr/local/bundle
      # - ~/.ssh/aws-ram-key.pem:/root/.ssh/aws-ram-key.pem
      # - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - 3000:3000
    links:
      - db
    tty: true
    stdin_open: true

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/partager
      - gem_data:/usr/local/bundle
    ports:
      - 3035:3035

volumes:
  mysql_data:
  gem_data:
