version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/partager
      - ~/.ssh/aws-ram-key.pem:/root/.ssh/aws-ram-key.pem
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - 3000:3000
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql_data:
