version: 2.1
executors:
  ruby_executor:
    docker:
      - image: cimg/ruby:3.0.2-browsers
  ruby_mysql_executor:
    docker:
      - image: cimg/ruby:3.0.2-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_PASSWORD: ""
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

commands:
  bundle_install:
    steps:
      - restore_cache:
          name: Restore bundle cache
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle

jobs:
  build:
    executor: ruby_executor
    working_directory: ~/partager
    steps:
      - checkout
      - bundle_install
  lint:
    executor: ruby_executor
    working_directory: ~/partager
    steps:
      - checkout
      - bundle_install
      - run:
          name: Install Reviewdog
          command: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - run:
          name: Run RuboCop
          command: bundle exec rubocop | ./bin/reviewdog -f=rubocop -reporter=github-pr-review
  test:
    executor: ruby_mysql_executor
    working_directory: ~/partager
    steps:
      - checkout
      - bundle_install
      - run:
          name: Run db create
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run RSpec
          command: bundle exec rspec
  production_deploy:
    executor: ruby_executor
    working_directory: ~/partager
    steps:
      - checkout
      - bundle_install
      - add_ssh_keys:
          fingerprints:
            - "67:07:87:8b:81:df:b2:c6:8e:77:9e:b7:bf:1d:3f:6a"
      - deploy:
          name: Run Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - build
      - production_deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master

