default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host: db
  username: root
  password: password

development:
  <<: *default
  database: partager_development

test:
  <<: *default
  database: partager_test
  host: <%= ENV['DB_HOST'] || db %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
